### ISSUE TITLE
Paths should be renamed according to new changes

### ISSUE THREAD

**Issue by binodmx** [mushthaq33/APIM#1]
Now publisher-new is changed to publisher and store is changed to devportal. 

![Screenshot from 2019-10-01 23-03-44](https://user-images.githubusercontent.com/36144069/65985670-e38b4900-e49f-11e9-87e7-d356516f409a.png)

![Screenshot from 2019-10-01 23-05-22](https://user-images.githubusercontent.com/36144069/65985873-5399cf00-e4a0-11e9-8391-c64475489bfe.jpg)

**Comment by mushthaq33** [comment]
Fixed with 9afba107dc51a654bc89f0704e8d31dc02957eb5
